model:
  name: DeepSeek-V2-Lite-Chat
  model_type: deepseek_v2

paths:
  checkpoint_dir: /home/mashun/vllm_project/checkpoints/DeepSeek-V2-Lite-Chat
  output_dir: /home/mashun/vllm_project/checkpoints/DeepSeek-V2-Lite-Chat-w4a8

runtime:
  num_workers: 4
  mode: quant # dequant | dequant+quant | quant (only support bf16)

quant:
  version: 2
  format:
    TN:
      - "re:model.layers.\\d+.mlp.experts.*"
      - "re:model.layers.\\d+.self_attn.*"
    NN: ~
  batch_size: 64
  block_size: 128
  group_size: -1
  symmetric: True
  class:
    int4:
      - "re:model.layers.\\d+.mlp.experts.*"
    int8: 
      - "re:model.layers.\\d+.self_attn.*"
  ignore: 
    - "re:model.embed_tokens.*"
    - "re:model.norm.*"
    - "re:lm_head.*"
    - "re:.*layernorm.*"
    - "re:model.layers.\\d+.mlp.gate\\..*"
    - "re:model.layers.\\d+.mlp.shared_experts.*"
    - "re:model.layers.\\d+.mlp.gate_proj.*"
    - "re:model.layers.\\d+.mlp.up_proj.*"
    - "re:model.layers.\\d+.mlp.down_proj.*"
   
dequant:
  ignore: ~