model:
  name: Kimi-K2-Thinking
  model_type: kimik2

paths:
  checkpoint_dir: /home/mashun/vllm_project/checkpoints/Kimi-K2-Thinking
  output_dir: /home/mashun/vllm_project/checkpoints/Kimi-K2-Thinking-w4a8

runtime:
  num_workers: 16
  mode: dequant+quant # dequant | dequant+quant | quant (only support bf16)

quant:
  version: 2
  format: 
    TN:
      - "re:model.layers.\\d+.mlp.experts.*"
      - "re:.*shared_experts.*"
      - "re:model.layers.\\d+.self_attn.q_a_proj.*"
      - "re:model.layers.\\d+.self_attn.q_b_proj.*"
      - "re:model.layers.\\d+.self_attn.kv_a_proj_with_mqa.*"
      - "re:model.layers.\\d+.self_attn.kv_b_proj.*"
      - "re:model.layers.\\d+.self_attn.o_proj.*"
      - "re:model.layers.\\d+.mlp.shared_experts.*"
      - "re:model.layers.\\d+.mlp.gate_proj.*"
      - "re:model.layers.\\d+.mlp.down_proj.*"
      - "re:model.layers.\\d+.mlp.up_proj.*"
    NN: ~
  batch_size: 64
  block_size: 128
  group_size: -1
  symmetric: True
  class:
    int4:
      - "re:model.layers.\\d+.mlp.experts.*"
    int8:
      - "re:.*shared_experts.*"
      - "re:model.layers.\\d+.self_attn.q_a_proj.*"
      - "re:model.layers.\\d+.self_attn.q_b_proj.*"
      - "re:model.layers.\\d+.self_attn.kv_a_proj_with_mqa.*"
      - "re:model.layers.\\d+.self_attn.kv_b_proj.*"
      - "re:model.layers.\\d+.self_attn.o_proj.*"
      - "re:model.layers.\\d+.mlp.shared_experts.*"
      - "re:model.layers.\\d+.mlp.gate_proj.*"
      - "re:model.layers.\\d+.mlp.down_proj.*"
      - "re:model.layers.\\d+.mlp.up_proj.*"
  ignore: 
    - "re:model.layers.\\d+.self_attn.q_a_layernorm.*"
    - "re:model.layers.\\d+.self_attn.kv_a_layernorm.*"
    - "re:model.layers.\\d+.input_layernorm.*"
    - "re:model.layers.\\d+.post_attention_layernorm.*"
    - "re:model.layers.\\d+.mlp.gate.weight"
    - "re:model.layers.\\d+.mlp.gate.e_score_correction_bias"
    - "re:model.layers.\\d+.self_attn.rotary_emb.inv_freq"
    - "re:model.embed_tokens.*"
    - "re:model.norm.*"
    - "re:lm_head.*"
    

dequant:
  ignore:
    - "re:lm_head.*"
    - "re:.*self_attn.*"
    - "re:.*shared_experts.*"
    - "re:.*mlp\\.(gate|up|gate_up|down)_proj.*"
    - "re:model.layers.\\d+.mlp.gate.e_score_correction_bias"
    - "re:model.layers.\\d+.input_layernorm.weight"
    - "re:model.layers.\\d+.post_attention_layernorm.weight"
    - "re:model.layers.\\d+.mlp.gate.weight"
    - "re:model.layers.\\d+.self_attn.rotary_emb.inv_freq"
    - "re:model.norm.*"
    - "re:model.layers.\\d+.self_attn.q_a_layernorm.*"
    - "re:model.layers.\\d+.self_attn.kv_a_layernorm.*"
    - "re:model.embed_tokens.*"